SicoinInets/Models/PermissionSet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicoinInets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionSet()
        {
            this.RolesPermissons = new HashSet<RolesPermisson>();
        }
    
        public int IdPermission { get; set; }
        public string sName { get; set; }
        public string sController { get; set; }
        public string sMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesPermisson> RolesPermissons { get; set; }
    }
}

SicoinInets/Controllers/PermissionSetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SicoinInets.Controllers;
using SicoinInets.Models;
using SicoinInets.Utilities;

namespace Sicoin.Controllers
{
    public class PermissionSetsController : GenericController
	{
        private DbSicoinEntities1 db = new DbSicoinEntities1();

        // GET: PermissionSets
        public ActionResult Index()
        {
			ViewBag.mesage = TempData["Mensaje"];
			return View(db.PermissionSets.ToList());
        }

       // GET: PermissionSets/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPermission,sName,sController,sMethod")] PermissionSet permissionSet)
        {
            if (ModelState.IsValid)
            {
				try
				{
					db.PermissionSets.Add(permissionSet);
					db.SaveChanges();
					TempData["Mensaje"] = new Alert("¡Exito!", "Permiso ingresado", Alert.Success);
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					ViewBag.mesage = new Alert("¡Alerta!", "Error al ingresar el permiso", Alert.Danger);
					return View();
				}

			}
			else
			{
				ViewBag.mesage = new Alert("¡Alerta!", "Ya existe el permiso", Alert.Danger);
				return View();
			}
			
        }

        // GET: PermissionSets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PermissionSet permissionSet = db.PermissionSets.Find(id);
            if (permissionSet == null)
            {
                return HttpNotFound();
            }
            return View(permissionSet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPermission,sName,sController,sMethod")] PermissionSet permissionSet)
        {
            if (ModelState.IsValid)
            {
				try
				{
					db.Entry(permissionSet).State = EntityState.Modified;
					db.SaveChanges();
					TempData["Mensaje"] = new Alert("¡Exito!", "Permiso editado", Alert.Success);
					return RedirectToAction("Index");
				}catch(Exception ex)
				{
					ViewBag.mesage = new Alert("¡Alerta!", "Error al editar el permiso", Alert.Danger);
					return View();
				}

			}
            return View(permissionSet);
        }

        // GET: PermissionSets/Delete/5
        public ActionResult Delete(int? id)
        {
			PermissionSet permissionSet = db.PermissionSets.Find(id);
			db.PermissionSets.Remove(permissionSet);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

	}
}

SicoinInets/Views/PermissionSets/Create.cshtml
@model SicoinInets.Models.PermissionSet

@{
    ViewBag.Title = "Crear Permiso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container-fluid">
            <diV class="row">
                <div class="col-md-12">
                    <div class="col-md-6"><h4>Nuevo permiso</h4></div>
                    <div class="col-md-6">
                        <a href="@Url.Action("Index","PermissionSets")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
                    </div>
                </div>
            </diV>
        </div>
    </div>
    <div class="panel-body">
        @if (ViewBag.mesage != null)
        {
            <div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible) { @Html.Raw("alert-dismissible") } " role="alert">
                @if (ViewBag.mesage.Dismissible)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                }
                <strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
            </div>
        }

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.sName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.sController, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.sController, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sController, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.sMethod, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.sMethod, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sMethod, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <input type="submit" value="Crear" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoinInets/Views/PermissionSets/Edit.cshtml
@model SicoinInets.Models.PermissionSet

@{
    ViewBag.Title = "Editar un permiso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6"><h4>Editar permiso</h4></div>
                <div class="col-md-6">
                    <a href="@Url.Action("Index","PermissionSets")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
                </div>
            </div>
        </div>
    </div>
    <div class=" panel-body">
        @if (ViewBag.mesage != null)
        {
            <div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible) { @Html.Raw("alert-dismissible") } " role="alert">
                @if (ViewBag.mesage.Dismissible)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                }
                <strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
            </div>
        }
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdPermission)

                <div class="form-group">
                    @Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.sName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.sController, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.sController, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sController, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.sMethod, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.sMethod, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sMethod, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoinInets/Views/PermissionSets/Index.cshtml
@model IEnumerable<SicoinInets.Models.PermissionSet>

@{
    ViewBag.Title = "Permisos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.mesage != null)
{
    <div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible)
                    {
                        @Html.Raw("alert-dismissible") } " role="alert">
        @if (ViewBag.mesage.Dismissible)
        {
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        }
        <strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
    </div>
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container-fluid">

            <div class="col-md-12">
                <div class="col-md-6">
                    <h4>Permisos</h4>
                </div>
                <div class="col-md-6">
                    <a href="@Url.Action("Create", "PermissionSets")">
                        <i class="fa fa-plus"></i> Crear permiso
                    </a>
                </div>
            </div>

        </div>
    </div>

    <div class="panel-body">
        <div class=" col-md-1">
        </div>
        <div class="table-responsive col-md-10">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th hidden>
                            @Html.DisplayNameFor(model => model.IdPermission)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.sName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.sController)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.sMethod)
                        </th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td hidden>
                                @Html.DisplayFor(modelItem => item.IdPermission)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sController)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sMethod)
                            </td>

                            <td class="pull-left">
                                <a href="@Url.Action("Edit", "PermissionSets", new { id = item.IdPermission})" data-toggle="tooltip" title="Editar"><i class="fa fa-edit"></i></a> |
                                <a style="color:darkred" href="@Url.Action("Delete", "PermissionSets", new { id = item.IdPermission})" class="Deleter" data-toggle="tooltip" title="Eliminar"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section scripts{
    <script>
        $(".Deleter").click(function (event) {
            if (!confirm("¿Está seguro que quiere eliminar?")) {
                event.preventDefault();
            }
        });
    </script>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $('table').DataTable(
                {
                    "order": [[1, "asc"]],
                    "language":
                    {
                        "sProcessing": "Procesando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "No se encontraron resultados",
                        "sEmptyTable": "Ningún dato disponible en esta tabla",
                        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": "",
                        "sInfoThousands": ",",
                        "sLoadingRecords": "Cargando...",
                        "oPaginate": {
                            "sFirst": "Primero",
                            "sLast": "Último",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        },
                        "oAria": {
                            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }
                    }
                });
        });
    </script>
}