SicoinInets/Models/ProfileSet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicoinInets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProfileSet
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileSet()
        {
            this.ProfileRoles = new HashSet<ProfileRole>();
            this.UserSets = new HashSet<UserSet>();
        }

        public int IdProfile { get; set; }

        [Required]
        [Display(Name = "Nombre de perfil")]
        [DisplayFormat(ConvertEmptyStringToNull = false, NullDisplayText = " ")]
        [RegularExpression(@"^[a-zA-ZñÑáÁéÉíÍóÓúÚäÄëËïÏöÖüÜ0-9\(\)\´\,\:\.\-\/\s\&\#\!\¡]{1,50}$",
            ErrorMessage = "Se permite la captura de  ( ) ´ , : . - /  & # ! ¡ con un máximo  de 50 caracteres.")]
        public string sName { get; set; }

        [Required]
        [Display(Name = "Descripción")]
        [DisplayFormat(ConvertEmptyStringToNull = false, NullDisplayText = " ")]
        [RegularExpression(@"^[a-zA-ZñÑáÁéÉíÍóÓúÚäÄëËïÏöÖüÜ0-9\(\)\´\,\:\.\-\/\s\&\#\!\¡]{1,200}$",
            ErrorMessage = "Se permite la captura de  ( ) ´ , : . - /  & # ! ¡ con un máximo  de 200 caracteres.")]
        public string sDescription { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileRole> ProfileRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSet> UserSets { get; set; }
    }
}

SicoinInets/Controllers/ProfileSetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using SicoinInets.Models;
using SicoinInets.Utilities;
using SicoinInets.Controllers;

namespace Sicoin.Controllers
{
    public class ProfileSetsController : GenericController
    {
        private DbSicoinEntities1 db = new DbSicoinEntities1();

        //Vista de pantalla principal de perfiles con un listado de datos ya dados de alta 
        public ActionResult Index()
        {
            ViewBag.mesage = TempData["Mensaje"];
            return View(db.ProfileSets.ToList());
        }

        //Vista de crear un nuevo perfil
        public ActionResult Create()
        {
            return View();
        }

        //Funcionalidad de crear un nuevo perfil esto lo conecta a la base de datos 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProfileSet pfiles)
        {
            ProfileSet pfil = db.ProfileSets.Where(item => item.sName == pfiles.sName).FirstOrDefault();
            if (pfil == null)
            {
                try
                {
                    db.ProfileSets.Add(pfiles);
                    db.SaveChanges();
                    TempData["Mensaje"] = new Alert("¡Notificación!", "Perfil ingresado", Alert.Success);
                    return RedirectToAction("Index");

                }
                catch
                {
                    ViewBag.mesage = new Alert("¡Alerta!", "Error al ingresar el perfil", Alert.Danger);
                    return View();

                }
            }
            else
            {
                ViewBag.mesage = new Alert("¡Alerta!", "Ya existe el perfil", Alert.Danger);
                return View();
            }
        }
		
        //Funcionalidad de eliminar desde la vista index manda la notificacion de eliminar y este hace la eliminacion del dato 
		public ActionResult Delete(int id)
		{
			try
			{
				ProfileRole profrol = db.ProfileRoles.Where(item => item.IdProfile == id).FirstOrDefault();
				if (profrol == null)
				{
					ProfileSet profiles = db.ProfileSets.Find(id);

					db.ProfileSets.Remove(profiles);
					db.SaveChanges();

					TempData["Mensaje"] = new Alert("¡Notificación!", "Perfil eliminado ", Alert.Success);
					return RedirectToAction("Index");
				}
				else
				{
					TempData["Mensaje"] = new Alert("¡Alerta!", "Error el perfil tiene roles asociados", Alert.Danger);
					return RedirectToAction("Index");
				}
			}
			catch
			{
				TempData["Mensaje"] = new Alert("¡Alerta!", "No se elimino el perfil", Alert.Danger);
				return RedirectToAction("Index");
			}
		}

        //Vista de editar donde pedimos el id del dato que fue dado de alta y hacemos una busqueda para mostrarlo en la vista 
        public ActionResult Edit(int id)
        {
            ProfileSet profile = db.ProfileSets.Find(id);
			return View(profile);
        }

        //Funcionalidad de editar donde recibe los datos para cambiarlos al dato que ya esta dado de alta 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProfileSet profile)
       {
			if(ModelState.IsValid)
			{
				try
				{
					db.Entry(profile).State = EntityState.Modified;
					db.SaveChanges();
					TempData["Mensaje"] = new Alert("¡Notificación!", "Perfil editado", Alert.Success);
					return RedirectToAction("Index");
				}
				catch(Exception ex)
				{
					ViewBag.mesage = new Alert("¡Alerta!", "Error al editar el permiso", Alert.Danger);
					return View();
				}
			}
			return View();
        }

        //Vista de seleccionar un rol creado donde cargas la lista de roles que fueron dados de alta 
        public ActionResult assignRole(int id = 0)
        {

            if (id == 0)
            {
                id = Convert.ToInt32(TempData["id"]);
            }
            ViewBag.mesage = TempData["Mensaje"];

            List<RolesSet> list = new List<RolesSet>();
            try
            {
                var ListRol = db.RolesSets.ToList();
                var ListProRol = db.ProfileRoles.Where(item => item.IdProfile == id).ToList();

                foreach (var item2 in ListProRol)
                {
                    foreach (var item in ListRol)
                    {
                        if (item.IdRole == item2.IdRole)
                        {
                            list.Add(item);
                            ListRol.Remove(item);
                            break;
                        }
                    }
                }

                if (ListProRol.Count != 0)
                {
                    ViewBag.RolSelected = list;
                }
                if (ListRol.Count != 0)
                {
                    ViewBag.Rol = ListRol;
                }

                ProfileSet profile = db.ProfileSets.Find(id);
                return View(profile);
            }
            catch
            {
                ViewBag.mesage = new Alert("¡Alerta!", "Error al obtener los datos", Alert.Danger);
                return View();
            }
        }

        //Funcionalidad para asignar un rol al perfil, se le asigna el rol y se adjuntan en la tabla 
        [HttpPost]
        public ActionResult AssignRole(ProfileRole Prorol, int[] Roles)
        {

            TempData["id"] = Prorol.IdProfile;
            try
            {
                if (Roles != null)
                {
                    foreach (var item in Roles)
                    {
                        ProfileRole objRol = new ProfileRole();
                        objRol.IdRole = item;
                        objRol.IdProfile = Prorol.IdProfile;
                        ProfileRole Rolper = db.ProfileRoles.Where(Values => Values.IdProfile == Prorol.IdProfile && Values.IdRole == item).FirstOrDefault();
                        if (Rolper == null)
                        {
                            db.ProfileRoles.Add(objRol);
                            db.SaveChanges();
                        }
                        else
                        {
                            return RedirectToAction("AssignRole");
                        }
                    }
                }
                return RedirectToAction("AssignRole");

            }
            catch
            {
                return View("AssignRole");
            }
        }

        //Funcion para des-asignar un rol del perfil que esta dado de alta 
		public ActionResult DeleteRol(int id, int idpro)
        {
            TempData["id"] = idpro;
            try
            {
                ProfileRole rolp = db.ProfileRoles.Where(item => item.IdRole == id && item.IdProfile == idpro).FirstOrDefault();
                //RolesPermissions rolperm = bd.RolesPermissionsSet.Find(id);
                db.ProfileRoles.Remove(rolp);
                db.SaveChanges();
                TempData["Mensaje"] = new Alert("¡Notificacion!", "Rol eliminado", Alert.Success);
                return RedirectToAction("AssignRole");
            }
            catch
            {
                ViewBag.mesage = new Alert("¡Alerta!", "Error al eliminar", Alert.Danger);
                return View("AssignRole");
            }

        }

    }
}

SicoinInets/Views/ProfileSets/Create.cshtml
@model SicoinInets.Models.ProfileSet

@{
    ViewBag.Title = "Nuevo perfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class=" panel panel-default">
	<div class="panel-heading">
		<div class=" container-fluid">
			<div class="row">

				<div class="col-md-12">
					<div class="col-md-10">
						<h4>Nuevo perfil</h4>
					</div>
					<div class="col-md-2">
						<a href="@Url.Action("Index","ProfileSets")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
					</div>
				</div>

			</div>
		</div>
	</div>
	@if (ViewBag.mesage != null)
	{
		<div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible)
                    {
                        @Html.Raw("alert-dismissible") } " role="alert">
			@if (ViewBag.mesage.Dismissible)
			{
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			}
			<strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
		</div>
	}

	<div class="panel-body">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			@using (Html.BeginForm())
			{
				@Html.AntiForgeryToken()

				<div class="form-horizontal">

					<div class="form-group">
						@Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.sName, new { htmlAttributes = new { @placeholder = "Escribir nombre", @class = "form-control", @maxlength = 50 } })
							@Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.sDescription, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.TextAreaFor(model => model.sDescription, new { @placeholder = "Escribir descripción", @class = "form-control", @maxlength = 250 })
							@Html.ValidationMessageFor(model => model.sDescription, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<button type="submit" class="btn btn-success">
								Guardar<i class="fa fa-check"></i>
							</button>
						</div>
					</div>
				</div>
			}


		</div>

	</div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoinInets/Views/ProfileSets/Edit.cshtml
@model SicoinInets.Models.ProfileSet

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
	<div class="panel-heading">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-10"><h4>Editar perfil</h4></div>
				<div class="col-md-2">
					<a href="@Url.Action("Index","ProfileSets")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
				</div>
			</div>
		</div>
	</div>
	@if (ViewBag.mesage != null)
	{
		<div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible) { @Html.Raw("alert-dismissible") } " role="alert">
			@if (ViewBag.mesage.Dismissible)
			{
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			}
			<strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
		</div>
	}
	<div class=" panel-body">

		<div class="col-md-2"></div>
		<div class="col-md-8">
			@using (Html.BeginForm())
			{
				@Html.AntiForgeryToken()

				<div class="form-horizontal">

					@Html.ValidationSummary(true, "", new { @class = "text-danger" })

					<div class="form-group" hidden>
						@Html.LabelFor(model => model.IdProfile, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-7" hidden>
							@Html.EditorFor(model => model.IdProfile, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.IdProfile, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.sName, new { htmlAttributes = new { @placeholder = "Escribir nombre", @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.sDescription, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.sDescription, new { htmlAttributes = new { @placeholder = "Escribir nombre", @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.sDescription, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<button type="submit" class="btn btn-success">
								Guardar<i class="fa fa-check"></i>
							</button>
						</div>
					</div>

				</div>
			}
		</div>
	</div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoinInets/Views/ProfileSets/Index.cshtml
@model IEnumerable<SicoinInets.Models.ProfileSet>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.mesage != null)
{
    <div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible)
                    {
                        @Html.Raw("alert-dismissible") } " role="alert">
        @if (ViewBag.mesage.Dismissible)
        {
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        }
        <strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
    </div>
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container-fluid">
            <div class="col-md-12">
                <div>
                    <h4> Perfiles</h4>
                </div>
                <div>
                    <a href="@Url.Action("Create","ProfileSets")">
                        <i class="fa fa-plus"></i> Nuevo perfil
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class=" col-md-1">
        </div>
        <div class="table-responsive col-md-10">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>
                            Opciones
                        </th>
                        <th style="width:30%">
                            Perfiles
                        </th>
                        <th style="width:40%">
                            Descripción
                        </th>
                        <th>Núm. de roles</th>
                        <th>
                            Roles
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <a href="@Url.Action("Edit", "ProfileSets", new { id = item.IdProfile})" data-toggle="tooltip" title="Editar"><i class="fa fa-edit"></i></a> |
                                <a style="color:darkred" href="@Url.Action("Delete", "ProfileSets", new { id = item.IdProfile})" class="Deleter" data-toggle="tooltip" title="Eliminar"><i class="fa fa-trash"></i></a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sDescription)
                            </td>
                            <td>@item.ProfileRoles.Count()</td>
                            <td class="text-left">
                                <a href="@Url.Action("assignRole", "ProfileSets", new { id = item.IdProfile })" class="text-info" data-toggle="tooltip" title="Nuevo rol" data-path="@item.sName" data-id="@item.IdProfile">
                                    <i class="fa fa-plus"></i> Roles
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@*<script>
        //$(document).ready(function () {
        $('table').DataTable();
               //});
    </script>*@
@Html.Partial("_ModalEdit")
@section scripts{
    <script>

        $(".Deleter").click(function (event) {
            if (!confirm("¿Está seguro que quiere eliminar?")) {
                event.preventDefault();
            }
        });
    </script>

    <script>
        $(".edit").on("click", function () {
            var id = $(this).data("idperfil");
            console.log(id);
            $.get("/ProfileSets/Edit", { id: id })
                .done(function (data) {
                    console.log(data);
                    $("#modal_editprof").modal("show");
                    $("#mybody").html(data);
                    $("#formBaseRoutesShops").trigger("reset");
                })
                .fail(function (XHR) {
                    validateErrorJS(XHR.status);
                })
        });
    </script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $('table').DataTable(
                {
                    "order": [[1, "asc"]],
                    "language":
                    {
                        "sProcessing": "Procesando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "No se encontraron resultados",
                        "sEmptyTable": "Ningún dato disponible en esta tabla",
                        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": "",
                        "sInfoThousands": ",",
                        "sLoadingRecords": "Cargando...",
                        "oPaginate": {
                            "sFirst": "Primero",
                            "sLast": "Último",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        },
                        "oAria": {
                            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }
                    }
                });
        });
    </script>
}

SicoinInets/Views/ProfileSets/_PartialEdit.cshtml
@model SicoinInets.Models.ProfileSet
<div>
    <form id="myform">

        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="form-group" hidden>
                @Html.LabelFor(model => model.IdProfile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-9" hidden>
                    @Html.EditorFor(model => model.IdProfile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdProfile, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class=" control-label col-md-2">Nombre</label>
                <div class="col-md-9">
                    <input placeholder="Escribir nombre" class="form-control" name="sName" id="sName" value="@Model.sName" maxlength="50"/>
                  </div>
            </div>

            <div class="form-group">
                <label class=" control-label col-md-2">Descripción</label>
                <div class="col-md-9">
                    <textarea placeholder="Escribir descripción" name="sDescriptiion" id="sDescriptiion" class="form-control" maxlength="250" rows="8">@Model.sDescription</textarea>
                   </div>
            </div>
          
            <div class="btn-toolbar" role="toolbar">
                <div class="btn-group pull-right">
                    <button type="submit" id="updateprof" class="btn btn-success submitBtn">Actualizar <i class="glyphicon glyphicon-ok"></i></button>
                </div>
            
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $("#myform").validate({
        rules: {
            sName: {
                required: true,
                maxlength: 50,
                PatternTest: /^[a-zA-ZñÑáÁéÉíÍóÓúÚäÄëËïÏöÖüÜ0-9\(\)\´\,\:\.\-\/\s\&\#\!\¡\*]{1,50}$/
            },
            sDescriptiion: {
                required: true,
                maxlength: 250,
                PatternTest: /^[a-zA-ZñÑáÁéÉíÍóÓúÚäÄëËïÏöÖüÜ0-9\(\)\´\,\:\.\-\/\s\&\#\!\¡\*]{1,250}$/
            },
            action: "required"
        },
        messages: {
            sName: {
                required: "El campo nombre es requerido",
                maxlength: "El tamaño máximo es de 20",
                PatternTest: "Se permite la captura de  ( ) ´ , : . - /  & # ! ¡ con un máximo de 50 caracteres."
            },
            sDescriptiion: {
                required: "El campo descripción es requerido",
                maxlength: "El tamaño máximo es de 250",
                PatternTest: "Se permite la captura de  ( ) ´ , : . - /  & # ! ¡ con un máximo de 50 caracteres."
            },
            action: "Ingresar datos"
        },
        submitHandler: function (form) {
            var myformdata = $("#myform").serialize();
            $.ajax({
                type: "POST",
                url: "/ProfileSets/Edit",
                data: myformdata,
                success: function () {
                    $("#modal_editprof").modal("hide");
                    location.reload();
                }
            });
        }

    });
      
</script>

SicoinInets/Views/ProfileSets/assignRole.cshtml
@model SicoinInets.Models.ProfileSet
@{
    ViewBag.Title = "Asociar roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-10">
            </div>
            <div class="col-md-2">
                <a href="@Url.Action("Index", "ProfileSets")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
            </div>
        </div>
    </div>

	<div class="panel-body">
		<div class=" col-md-2"></div>
		<div class=" col-md-8">
			@using (Html.BeginForm("assignRole", "ProfileSets", FormMethod.Post, new { @id = "addRols" }))
			{
				@Html.AntiForgeryToken()

				<div class="form-horizontal">

					@Html.ValidationSummary(true, "", new { @class = "text-danger" })

					<div class="form-group" hidden>
						@Html.LabelFor(model => model.IdProfile, htmlAttributes: new { @class = "control-label col-md-2" })
						<div>
							@Html.EditorFor(model => model.IdProfile, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.IdProfile, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<label class=" control-label col-md-3">Perfil</label>
						<div class="col-md-8">
							@Html.EditorFor(model => model.sName, new { htmlAttributes = new { @Value = Model.sName, @class = "form-control", @readonly = "readonly" } })
							@Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<label class=" control-label col-md-3">
							Seleccionar roles
							<a style="color:black" data-toggle="tooltip" title="Para seleccionar varias opciones presione la tecla ctrl + clic"><i class="glyphicon glyphicon-question-sign"></i></a>
						</label>
						<div class="col-md-8">
							<select name="Roles" class="form-control" id="multisel" multiple required>

								@if (ViewBag.Rol != null)
								{
									foreach (var rol in ViewBag.Rol)
									{
										<option value="@rol.IdRole">@rol.sName</option>
									}
								}
							</select>
						</div>
					</div>
					<div class="form-group">
						@if (ViewBag.Rol != null)
						{
							<div class="col-md-offset-2 col-md-10">
								<button type="submit" class="btn btn-success pull-right">
									Agregar <i class="glyphicon glyphicon-plus"></i>
								</button>
							</div>
						}
					</div>
				</div>
			}
		</div>
		</div>
	</div>

<div class="col-md-2"></div>

<div class=" col-md-8">
	@if (ViewBag.RolSelected != null)
	{
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="container-fluid">
					<div class="col-md-4">Role(s) asociado(s) al perfil</div>
					<div class="col-md-8"><b class="pull-right">@ViewBag.RolSelected.Count</b></div>
				</div>
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class=" table table-striped table-hover table-bordered">
						<thead>
							<tr>
								<th hidden>
									Id rol
								</th>
								<th>
									Roles asociados
								</th>
								<th>
									Opción
								</th>
							</tr>
						</thead>
						<tbody>
							@if (ViewBag.RolSelected != null)
							{
								foreach (var item in ViewBag.RolSelected)
								{

									<tr>
										<td hidden>
											@item.IdRole
										</td>
										<td>
											@item.sName
										</td>
										<td>
											<a href="@Url.Action("DeleteRol", "ProfileSets", new { id = item.IdRole, idpro = Model.IdProfile })" class="Deleter text-danger" data-toggle="tooltip" title="Desasociar rol"><i class="glyphicon glyphicon-minus"> </i> Desasociar</a>
										</td>
									</tr>

								}
							}
						</tbody>
					</table>
				</div>

			</div>
		</div>
	}
</div>



@section jsslocal {
    <script>
        $(".Deleter").click(function (event) {
            if (!confirm("¿Está seguro que quiere desasociar?")) {
                event.preventDefault();
            }
        });
    </script>
    <script>
        $(function () {
            $("#addRols").on("submit", function (e) {
                var boton = new Boton();
                boton.disabled("#addRols");
            });
        });
    </script>
    <script>
        $('[data-toggle="tooltip"]').tooltip();
    </script>
}