SicoinInets/Controllers/FulfillmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data.Entity;
using SicoinInets.Models;
using SicoinInets.Utilities;
using SicoinInets.Controllers;

namespace SicoinInets.Controllers
{
    public class FulfillmentController : Controller
    {
        DbSicoinEntities1 db = new DbSicoinEntities1();

        // GET: Fulfillment
        public ActionResult Index()
        {
            ViewBag.mesage = TempData["Mensaje"];

            List<typeFulfillment> type = db.typeFulfillments.ToList();
            return View(type.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(typeFulfillment type)
        {
            typeFulfillment type2 = db.typeFulfillments.Where(x => type.sName == x.sName).FirstOrDefault();

            if (type2 == null)
            {
                try
                {
                    db.typeFulfillments.Add(type);
                    db.SaveChanges();

                    TempData["Mensaje"] = new Alert("¡Notificación!", "Rango de cumplimiento creado", Alert.Success);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.mesage = new Alert("¡Alerta!", "Error al generarun nuevo rango ", Alert.Danger);
                    return View();
                }
            }
            else
            {
                ViewBag.mesage = new Alert("¡Alerta!", "Ya existe un rango con este nombre", Alert.Danger);
                return View();
            }

        }

        public ActionResult Edit(int idtype)
        {
            typeFulfillment type2 = db.typeFulfillments.Find(idtype);
            return View(type2);
        }

        [HttpPost]
        public ActionResult Edit(typeFulfillment type)
        {
            DbSicoinEntities1 db = new DbSicoinEntities1();

            typeFulfillment type2 = db.typeFulfillments.Find(type.idTimefulfil);
            
            typeFulfillment tf1 = db.typeFulfillments.Where(x=>x.sName == "Sala de espera").FirstOrDefault();
            typeFulfillment tf2 = db.typeFulfillments.Where(x => x.sName == "Abordando").FirstOrDefault();
            typeFulfillment tf3 = db.typeFulfillments.Where(x => x.sName == "Retrasado").FirstOrDefault();
            try
            {
                if (type2.sName == "Sala de espera")
                {
                    if (tf2.dayfinish < type.dayfinish)
                    {
                        type2.dayfinish = type.dayfinish;
                        db.Entry(type2).State = EntityState.Modified;
                        db.SaveChanges();

                        TempData["Mensaje"] = new Alert("¡Notificación!", "Datos del rango editado", Alert.Success);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Mensaje"] = new Alert("¡Alerta!", "La fecha debe ser mayor al estado de abordando", Alert.Danger);
                        return RedirectToAction("Index");
                    }
                }

                if (type2.sName == "Abordando")
                {
                    if (tf3.dayfinish < type.dayfinish && tf1.dayfinish > type.dayfinish)
                    {
                        type2.dayfinish = type.dayfinish;
                        db.Entry(type2).State = EntityState.Modified;
                        db.SaveChanges();

                        TempData["Mensaje"] = new Alert("¡Notificación!", "Datos del rango editado", Alert.Success);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Mensaje"] = new Alert("¡Alerta!", "La fecha debe ser mayor al estado de retrasado y menor que sala de espera", Alert.Danger);
                        return RedirectToAction("Index");
                    }
                }

                if (type2.sName == "Retrasado")
                {
                    if (tf2.dayfinish > type.dayfinish)
                    {
                        type2.dayfinish = type.dayfinish;
                        db.Entry(type2).State = EntityState.Modified;
                        db.SaveChanges();

                        TempData["Mensaje"] = new Alert("¡Notificación!", "Datos del rango editado", Alert.Success);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Mensaje"] = new Alert("¡Alerta!", "La fecha debe ser menor al estado de abordando", Alert.Danger);
                        return RedirectToAction("Index");
                    }
                }
                TempData["Mensaje"] = new Alert("¡Alerta!", "Cumpla con los campos de edición", Alert.Danger);
                return RedirectToAction("Index");

            }
            catch(Exception ex)
            {
                TempData["Mensaje"] = new Alert("¡Alerta!", "Error al editar rango de cumplimiento", Alert.Danger);
                return RedirectToAction("Index");
            }
        }
    }
}

SicoinInets/Views/Fulfillment/Create.cshtml
@model SicoinInets.Models.typeFulfillment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
	<div class="panel-heading">
		<div class="container-fluid">
			<div class=" row">
				<h4>Nuevo rango de cumplimiento</h4>
				<a href="@Url.Action("Index","Fulfillment")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
			</div>
		</div>
	</div>
	@if (ViewBag.mesage != null)
	{
		<div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible)
                    {
                        @Html.Raw("alert-dismissible") } " role="alert">
			@if (ViewBag.mesage.Dismissible)
			{
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			}
			<strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
		</div>
	}

	<div class="panel-body">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			@using (Html.BeginForm())
			{
				@Html.AntiForgeryToken()

				<div class="form-horizontal">
					<hr />
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })

					<div class="form-group">
						@Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.sName, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.dayinitial, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.dayinitial, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.dayinitial, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.dayfinish, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.dayfinish, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.dayfinish, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="Guardar" class="btn btn-success" />
						</div>
					</div>
				</div>
			}

		</div>


	</div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SicoinInets/Views/Fulfillment/Edit.cshtml
@model SicoinInets.Models.typeFulfillment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
	<div class=" panel-heading">
		<div class=" container-fluid">
			<div class="row">
				<h4>Editar un rango de cumplimiento</h4>
				<a href="@Url.Action("Index","Fulfillment")" class="pull-right"><i class="glyphicon glyphicon-arrow-left"></i> Regresar</a>
			</div>
		</div>
	</div>
	@if (ViewBag.mesage != null)
	{
		<div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible)
                    {
                        @Html.Raw("alert-dismissible") } " role="alert">
			@if (ViewBag.mesage.Dismissible)
			{
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			}
			<strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
		</div>
	}

		<div class="panel-body">

			<div class="col-md-2"></div>
			<div class="col-md-8">
				@using (Html.BeginForm())
				{
					@Html.AntiForgeryToken()

					<div class="form-horizontal">
						
						<hr />
						@Html.ValidationSummary(true, "", new { @class = "text-danger" })
						<div class="form-group" hidden>
							@Html.LabelFor(model => model.idTimefulfil, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.idTimefulfil, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.idTimefulfil, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="form-group">
							@Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.sName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
								@Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="form-group">
							@Html.LabelFor(model => model.dayfinish, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.dayfinish, new { htmlAttributes = new { @class = "form-control", id = "dfinish" } })
								@Html.ValidationMessageFor(model => model.dayfinish, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<input type="submit" value="Guardar" class="btn btn-success" onclick="comparar()" />
							</div>
						</div>
					</div>
				}
			</div>
			</div>
		</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
	function comparar() {
		var textdf = $('#dfinish').val();

		if (textdf == null || textdf == 0) {
			alert("Error la fecha final no puede ser 0 ");
		}
	}
</script>
}

SicoinInets/Views/Fulfillment/Index.cshtml
@model IEnumerable<SicoinInets.Models.typeFulfillment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="container-fluid">
			<h4>Tipo de cumplimiento</h4>
		</div>
	</div>

	@if (ViewBag.mesage != null)
	{
		<div class="notify @ViewBag.mesage.Type @if (ViewBag.mesage.Dismissible)
                    {
                        @Html.Raw("alert-dismissible") } " role="alert">
			@if (ViewBag.mesage.Dismissible)
			{
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			}
			<strong>@ViewBag.mesage.Title</strong> @ViewBag.mesage.Description
		</div>
	}


		<div class="panel-body">
			<div class="table-responsive">
				<div class=" col-md-2"></div>

				<div class=" col-md-8">
					<table class=" table table-striped table-hover table-bordered">
						<thead>
							<tr>
								<th>
									@Html.DisplayNameFor(model => model.sName)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.dayfinish)
								</th>

								<th>Opciones</th>
							</tr>
						</thead>

						<tbody>
							@foreach (var item in Model)
							{
								if (item.dayfinish > 0)
								{
									<tr>
										<td>
											@Html.DisplayFor(modelItem => item.sName)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.dayfinish)
										</td>
										<td>
											<a href="@Url.Action("Edit", "Fulfillment", new { idtype = item.idTimefulfil})" data-toggle="tooltip" title="Editar"><i class="fa fa-edit"></i></a>
										</td>
									</tr>

								}
							}

						</tbody>
					</table>
				</div>
				
			</div>
			<div class="panel-footer">
				<h5><strong>Los tiempos de cumplimiento son los días que tiene para cumplir la tarea y deben cumplir el siguiente criterio</strong></h5>
				<h5><strong>* Sala de espera sea mayor que abordando</strong></h5>
				<h5><strong>* Abordando sea mayor que retrasado</strong></h5>
				<h5><strong>* Retrasado sea menor que abordando</strong></h5>
			</div>
		</div>
</div>