SicoinInets/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SicoinInets.Models;
using SicoinInets.Utilities;
using System.Data.Entity;
using SicoinInets.Sends;
using SicoinInets.Bussines;

using System.IO;


namespace SicoinInets.Controllers
{
    public class TaskController : Controller
    {
        DbSicoinEntities1 bd = new DbSicoinEntities1();
        private string folder = "Temp";

        // Pantalla principal para mostrar las listas de los status que tiene el sistema 3
        public ActionResult Monitor()
        {
            Consults consults = new Consults();
            int iduser = Convert.ToInt16(Session["Id"]);
            ViewBag.iduser = Convert.ToInt16(Session["Id"]);
            List<typeFulfillment> stats = bd.typeFulfillments.ToList();

           foreach(var item in stats)
            {
                foreach(var item2 in consults.countstask(iduser))
                {
                    if (item.sName == "Buzón de tareas" && item.idTimefulfil == item2.idtask)
                    {
                        ViewBag.counts = (item2.counter > 0) ? item2.counter :0;
                    }
                    if (item.sName == "Sala de espera" && item.idTimefulfil == item2.idtask)
                    {
                        ViewBag.counts2 = (item2.counter > 0) ? item2.counter : 0; ;
                    }
                    if (item.sName == "Abordando" && item.idTimefulfil == item2.idtask)
                    {
                        ViewBag.counts3 = (item2.counter > 0) ? item2.counter : 0; ;
                    }
                    if (item.sName == "Retrasado" && item.idTimefulfil == item2.idtask)
                    {
                        ViewBag.counts4 = (item2.counter > 0) ? item2.counter : 0; ;
                    }
                    if (item.sName == "Enviado" && item.idTimefulfil == item2.idtask)
                    {
                        ViewBag.counts5 = (item2.counter > 0) ? item2.counter : 0; ;
                    }
                    if (item.sName == "Verificado" && item.idTimefulfil == item2.idtask )
                    {
                        ViewBag.counts6 = (item2.counter > 0) ? item2.counter : 0; ;
                    }
                    if (item.sName == "Cancelado" && item.idTimefulfil == item2.idtask)
                    {
                        ViewBag.counts7 = (item2.counter > 0) ? item2.counter : 0; ;
                    }
                }
            }
           
            ViewBag.mesage = TempData["Mensaje"];
            return View();
        }

        //Al dar clic en cada boton te muestra los status que se quiere consultar solo mostrara las tareas que tiene asignada 
        public ActionResult Lstatus(int range, int id)
        {
            Consults consults = new Consults();
            DbSicoinEntities1 db = new DbSicoinEntities1();

            int iduser = Convert.ToInt16(Session["Id"]);
            ViewBag.iduser = Convert.ToInt16(Session["Id"]);
            ViewBag.range = range;
            List<task> tasks = consults.tasklist(iduser, range);

            return PartialView("Lstatus",tasks);
        }
        
        //Vista de la pantalla de crear tareas 
        public ActionResult Create()
        {
            int idus = Convert.ToInt16(Session["Id"]);

            ViewBag.iduser = Convert.ToInt16(Session["Id"]);
            ViewBag.userp = bd.UserSets.ToList();
            ViewBag.user = bd.UserSets.Where(x => x.IdUser != idus);
            ViewBag.timerdate = DateTime.UtcNow;
            return View();
        }

        //Funcion de crear una tarea y asignarlo a un usuario
        [HttpPost]
        public ActionResult Create(task task)
        {
            try
            {
                Mail mail = new Mail();

                ViewBag.user = bd.UserSets.ToList();
                ViewBag.userp = bd.UserSets.ToList();

                task.DateEmision = DateTime.Now.Date;
                task.idTimefulfil = 1;
                
                bd.tasks.Add(task);
                bd.SaveChanges();

                task task2 = bd.tasks.Where(x => x.sNameTask == task.sNameTask).FirstOrDefault();

                string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon),Convert.ToInt32(task.idTimefulfil),task2.Idtask);

                TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea agregada "+ message , Alert.Success);
                return RedirectToAction("Monitor");
            }
            catch
            {
                TempData["Mensaje"] = new Alert("¡Alerta!", " Valide que los datos estan completos", Alert.Danger);
                return RedirectToAction("Monitor");
            }
        }
       
        //RANGOS DE CUMPLIMIENTO CADA FUNCION QUE DEBE REALIZAR EL SISTEMA CON EL MONITOR-------------------------------------------
        
        //Funcion de aceptar la tarea y validar de que rango de fechas se esta ingresando el rango de cumpimiento
        public ActionResult AceptTask(int idtask)
        {
            try
            {
                Mail mail = new Mail();
                task task = bd.tasks.Find(idtask);
                DateTime now = DateTime.UtcNow;

                TimeSpan ts = Convert.ToDateTime(task.dDelivery) - now;

                typeFulfillment type = bd.typeFulfillments.Where(x => x.dayfinish > 0 && x.dayfinish < Math.Abs(ts.Days) ).FirstOrDefault();

                if (type == null)
                {
                    task.idTimefulfil = 5;
                    bd.SaveChanges();

                    string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon), Convert.ToInt32(task.idTimefulfil),task.Idtask);

                    TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea aceptada y agregada a retrasado", Alert.Success);

                    return RedirectToAction("Monitor");
                }else
                {
                    if (type.idTimefulfil == 3)
                    {
                        task.idTimefulfil = 3;
                        bd.SaveChanges();

                        string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon), Convert.ToInt32(task.idTimefulfil), task.Idtask);

                        TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea aceptada y agregada en sala de espera", Alert.Success);

                        return RedirectToAction("Monitor");

                    }
                    else
                    if (type.idTimefulfil == 4)
                    {
                        task.idTimefulfil = 3;
                        bd.SaveChanges();

                        string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon), Convert.ToInt32(task.idTimefulfil), task.Idtask);

                        TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea aceptada y agregada en sala de espera", Alert.Success);

                        return RedirectToAction("Monitor");

                    }
                    else if (type.idTimefulfil == 5)
                    {
                        task.idTimefulfil = 4;
                        bd.SaveChanges();

                        string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon), 2, task.Idtask);

                        TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea aceptada y agregada a abordando", Alert.Success);
                        return RedirectToAction("Monitor");
                    }
                }

                TempData["Mensaje"] = new Alert("¡Alerta!", " Surgio un error al crear la tarea", Alert.Danger);
                return RedirectToAction("Monitor");
            }
            catch
            {
                ViewBag.mesage = new Alert("¡Alerta!", " Valide que los datos estan completos", Alert.Danger);
                return RedirectToAction("Monitor");
            }
        }
        
        //Funcion para enviar la tarea
        public ActionResult pEnviar(int idtask)
        {
            try
            {
                task task = bd.tasks.Find(idtask);
                Mail mail = new Mail();
                
                task.idTimefulfil = 6;
                bd.SaveChanges();

                string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon), Convert.ToInt32(task.idTimefulfil), task.Idtask);

                TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea enviada", Alert.Success);
                return RedirectToAction("Monitor");

            }catch(Exception ex)
            {
                TempData["Mensaje"] = new Alert("¡Alerta!", " Hubo un error en generar el envio de la tarea reinicie la sesion", Alert.Success);
                return RedirectToAction("Monitor");
            }

        }

        //Funcion para finalizar la tarea
        public ActionResult Finalitytask(int idtask)
        {
            try
            {
                task task = bd.tasks.Find(idtask);
                Mail mail = new Mail();

                task.idTimefulfil = 7;
                bd.SaveChanges();

                string message = mail.enviar(Convert.ToInt32(task.idUser), Convert.ToInt32(task.idUserRespon), Convert.ToInt32(task.idTimefulfil), task.Idtask);

                TempData["Mensaje"] = new Alert("¡Notificación!", " Tarea terminada", Alert.Success);
                return RedirectToAction("Monitor");

            }
            catch (Exception ex)
            {
                TempData["Mensaje"] = new Alert("¡Alerta!", " Hubo un error al finalizar la tarea", Alert.Success);
                return RedirectToAction("Monitor");
            }

        }

        //Funcion para indicar que esta incompleta y regresarlos a enviado
        public ActionResult IncompleteTask(int idtask)
        {

SicoinInets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Control interno</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Styles.Render("~/Content/jquery-ui.css")


	@*<style>
			body {
				padding: 0;
				margin: 0;
			}
		</style>*@
</head>
<body>
    <div id="wrapper" class="in">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"> <i class="fa fa-cube" style=" color:#819cf5"></i> SICOIN</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><a href="@Url.Action("Threefile","UrlsSets")"><i class="fa fa-sitemap"></i> Flujo de Procesos <span class="sr-only"></span></a></li>
						<li><a href="@Url.Action("Index","UrlsSets")"><i class="fa fa-folder"></i> Carpetas <span class="sr-only"></span></a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-cog"></i> Mantenimiento <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="@Url.Action("Index","RolesSets")"><i class="fa fa-bullhorn"></i> Roles</a></li>
								<li><a href="@Url.Action("Index","ProfileSets")"><i class="fa fa-paperclip"></i> Perfiles</a></li>
								<li><a href="@Url.Action("Index","User")"><i class="fa fa-user"></i> Usuarios</a></li>
								<li><a href="@Url.Action("Index","Email")"><i class="glyphicon glyphicon glyphicon-envelope"></i> Servidor de correo</a></li>
								<li><a href="@Url.Action("Index","Fulfillment")"><i class="glyphicon glyphicon-time"></i> Rangos de cumplimiento</a></li>
							</ul>
						</li>
						<li><a href="@Url.Action("Monitor","Task")"><i class="fa fa-television"></i> Monitor <span class="sr-only"></span></a></li>
					</ul>
                    <ul>
                       
                        @if (Session["Id"] != null)
                        {
                        <li class="pull-right">
                            <h5>
                                <a href="@Url.Action("LogOut", "LogIn")" data-toggle="tooltip" data-placement="bottom" title="Cerrar sesión">
                                    @Session["Name"] <i class="fa fa-sign-out"></i>
                                </a>
                            </h5>
                        </li>
                        }
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("jsslocal", required: false)
    @RenderSection("htmllocal", required: false)
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @RenderSection("jsslocal", required: false)
        @RenderSection("htmllocal", required: false)*@


    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

SicoinInets/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Control interno</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")


    <style>
        body {
            padding: 0;
            margin: 0;
        }
    </style>
</head>
<body>
    <div id="wrapper" class="in">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-static-top" style="margin-bottom: 0">
            
        </nav>
    </div>
    <div class="container body-content">
        @*@RenderBody()*@
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
            </footer>*@
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @RenderSection("jsslocal", required: false)
        @RenderSection("htmllocal", required: false)*@
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

SicoinInets/Views/Shared/_LoadAnswer.cshtml
<style>
	img.load {
		clear: right;
		float: right;
		position: relative;
		right: 10%;
	}
</style>
<div id="loader" style="display:none;">
	<img src="~/Content/img/Spinner-1s-48px.gif" class="load" />
</div>

<div id="_notify" role="alert" style="display:none;">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<div id="errors"></div>
</div>

SicoinInets/Views/Shared/_ModalEdit.cshtml
<!-- Modal -->
<div id="modal_edit" class="modal fade bs-example-modal-sm" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Editar rol</h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body" id="modalbodyrol">
                <p class="statusMsg"></p>
                <form role="form">
                    <input type="hidden" name="Id" />
                    <div class="form-group">
                        <label for="inputName">Nombre</label>
                        <input type="text" class="form-control" name="Name" required data-val="true" data-val-required="El campo nombre es obligatorio." />
                    </div>
                    <div class="form-group">
                        <label for="inputDesc">Descripción</label>
                        <textarea class="form-control" name="Description" required data-val="true" data-val-required="El campo descripción es obligatorio."></textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal_user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Editar Usuario</h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body" id="mymodalbody">
                <p class="statusMsg"></p>
                <form role="form">
                    <input type="hidden" name="Id" />
                    <div class="form-group">
                        <label for="inputName">Nombre</label>
                        <input type="text" class="form-control" name="Name" required data-val="true" data-val-required="El campo nombre es obligatorio." />
                    </div>
                    <div class="form-group">
                        <label for="inputDesc">Descripción</label>
                        <textarea class="form-control" name="Description" required data-val="true" data-val-required="El campo descripción es obligatorio."></textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="modal_editprof" class="modal fade" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Editar perfil</h4>
            </div>
            <div class="modal-body" id="mybody">              
            </div>
        </div>
    </div>
</div>

SicoinInets/Views/Shared/_OverWriteLoadData.cshtml
<div id="modal_confirmation" class="modal fade" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">
					<i class="glyphicon glyphicon-alert"></i>
				</h4>
			</div>
			<div class="modal-body">

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button id="aceptar" type="button" class="btn btn-success">Aceptar</button>
			</div>
		</div>
	</div>
</div>

<div id="modal_reconfirmation" class="modal fade bs-example-modal-sm" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="container-fluid">
					<div class="col-xs-2" style="color:#f0ad4e;">
						<i class="fa fa-4x fa-warning"></i>
					</div>
					<div class="col-xs-9">
						<br />
						<div class=""><div></div></div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button id="reaceptar" type="button" class="btn btn-warning">Aceptar</button>
			</div>
		</div>
	</div>
</div>

<div id="modal_stamp" class="modal fade bs-example-modal-sm" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="container-fluid">
					<div class="col-xs-2" style="color:#33A5FF;">
						<i class="fa fa-4x fa-info-circle"></i>
					</div>
					<div class="col-xs-9">
						<br />
						<div class=""><div></div></div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
			</div>
		</div>
	</div>
</div>

<div id="modal_stampnext" class="modal fade bs-example-modal-sm" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="container-fluid">
					<div class="col-xs-2" style="color:#33A5FF;">
						<i class="fa fa-4x fa-info-circle"></i>
					</div>
					<div class="col-xs-9">
						<br />
						<div class=""><div>  </div></div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
			</div>
		</div>
	</div>
</div>

SicoinInets/Views/Shared/_ShowErroresLoadFile.cshtml
<div class="panel panel-danger" id="_msns" style="display:none;">
	<div class="panel-heading">
		<div class="container-fluid">
			<div class="col-sm-9">¡Revisar!</div>
			<div class="col-sm-3" id="numerrors"></div>
		</div>

	</div>
	<div class="panel-body">
		<div class="container-fluid" id="_msn">
		</div>
	</div>
</div>